// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tars2node(20190529)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "DataService.tars" by Structure Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");

var _hasOwnProperty = Object.prototype.hasOwnProperty;

var LifeService = LifeService || {};
module.exports.LifeService = LifeService;

LifeService.UserInfo = function() {
    this.name = "";
    this.phone = "";
    this.gender = "";
    this.avatar_url = "";
    this.registration_time = "";
    this.group = 0;
    this._classname = "LifeService.UserInfo";
};
LifeService.UserInfo._classname = "LifeService.UserInfo";
LifeService.UserInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
LifeService.UserInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
LifeService.UserInfo._readFrom = function (is) {
    var tmp = new LifeService.UserInfo;
    tmp.name = is.readString(0, true, "");
    tmp.phone = is.readString(1, true, "");
    tmp.gender = is.readString(2, true, "");
    tmp.avatar_url = is.readString(3, true, "");
    tmp.registration_time = is.readString(4, true, "");
    tmp.group = is.readInt32(5, true, 0);
    return tmp;
};
LifeService.UserInfo.prototype._writeTo = function (os) {
    os.writeString(0, this.name);
    os.writeString(1, this.phone);
    os.writeString(2, this.gender);
    os.writeString(3, this.avatar_url);
    os.writeString(4, this.registration_time);
    os.writeInt32(5, this.group);
};
LifeService.UserInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
LifeService.UserInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
LifeService.UserInfo.prototype.toObject = function() { 
    return {
        "name" : this.name,
        "phone" : this.phone,
        "gender" : this.gender,
        "avatar_url" : this.avatar_url,
        "registration_time" : this.registration_time,
        "group" : this.group
    };
};
LifeService.UserInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "name") && (this.name = json.name);
    _hasOwnProperty.call(json, "phone") && (this.phone = json.phone);
    _hasOwnProperty.call(json, "gender") && (this.gender = json.gender);
    _hasOwnProperty.call(json, "avatar_url") && (this.avatar_url = json.avatar_url);
    _hasOwnProperty.call(json, "registration_time") && (this.registration_time = json.registration_time);
    _hasOwnProperty.call(json, "group") && (this.group = json.group);
    return this;
};
LifeService.UserInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
LifeService.UserInfo.new = function () {
    return new LifeService.UserInfo();
};
LifeService.UserInfo.create = function (is) {
    return LifeService.UserInfo._readFrom(is);
};

LifeService.Column = function() {
    this.columnName = "";
    this.DBInt = true;
    this.columnValue = "";
    this._classname = "LifeService.Column";
};
LifeService.Column._classname = "LifeService.Column";
LifeService.Column._write = function (os, tag, value) { os.writeStruct(tag, value); };
LifeService.Column._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
LifeService.Column._readFrom = function (is) {
    var tmp = new LifeService.Column;
    tmp.columnName = is.readString(0, true, "");
    tmp.DBInt = is.readBoolean(1, true, true);
    tmp.columnValue = is.readString(2, true, "");
    return tmp;
};
LifeService.Column.prototype._writeTo = function (os) {
    os.writeString(0, this.columnName);
    os.writeBoolean(1, this.DBInt);
    os.writeString(2, this.columnValue);
};
LifeService.Column.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
LifeService.Column.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
LifeService.Column.prototype.toObject = function() { 
    return {
        "columnName" : this.columnName,
        "DBInt" : this.DBInt,
        "columnValue" : this.columnValue
    };
};
LifeService.Column.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "columnName") && (this.columnName = json.columnName);
    _hasOwnProperty.call(json, "DBInt") && (this.DBInt = json.DBInt);
    _hasOwnProperty.call(json, "columnValue") && (this.columnValue = json.columnValue);
    return this;
};
LifeService.Column.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
LifeService.Column.new = function () {
    return new LifeService.Column();
};
LifeService.Column.create = function (is) {
    return LifeService.Column._readFrom(is);
};

LifeService.ClubInfo = function() {
    this.clubId = "";
    this.name = "";
    this.chairman = "";
    this.createTime = "";
    this.introduction = "";
    this._classname = "LifeService.ClubInfo";
};
LifeService.ClubInfo._classname = "LifeService.ClubInfo";
LifeService.ClubInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
LifeService.ClubInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
LifeService.ClubInfo._readFrom = function (is) {
    var tmp = new LifeService.ClubInfo;
    tmp.clubId = is.readString(0, true, "");
    tmp.name = is.readString(1, true, "");
    tmp.chairman = is.readString(2, true, "");
    tmp.createTime = is.readString(3, true, "");
    tmp.introduction = is.readString(4, true, "");
    return tmp;
};
LifeService.ClubInfo.prototype._writeTo = function (os) {
    os.writeString(0, this.clubId);
    os.writeString(1, this.name);
    os.writeString(2, this.chairman);
    os.writeString(3, this.createTime);
    os.writeString(4, this.introduction);
};
LifeService.ClubInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
LifeService.ClubInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
LifeService.ClubInfo.prototype.toObject = function() { 
    return {
        "clubId" : this.clubId,
        "name" : this.name,
        "chairman" : this.chairman,
        "createTime" : this.createTime,
        "introduction" : this.introduction
    };
};
LifeService.ClubInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "clubId") && (this.clubId = json.clubId);
    _hasOwnProperty.call(json, "name") && (this.name = json.name);
    _hasOwnProperty.call(json, "chairman") && (this.chairman = json.chairman);
    _hasOwnProperty.call(json, "createTime") && (this.createTime = json.createTime);
    _hasOwnProperty.call(json, "introduction") && (this.introduction = json.introduction);
    return this;
};
LifeService.ClubInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
LifeService.ClubInfo.new = function () {
    return new LifeService.ClubInfo();
};
LifeService.ClubInfo.create = function (is) {
    return LifeService.ClubInfo._readFrom(is);
};

LifeService.ActivityInfo = function() {
    this.activityId = "";
    this.sponsor = "";
    this.clubId = "";
    this.targetId = "";
    this.createTime = "";
    this.startTime = "";
    this.stopTime = "";
    this.registryStartTime = "";
    this.registryStopTime = "";
    this.content = "";
    this._classname = "LifeService.ActivityInfo";
};
LifeService.ActivityInfo._classname = "LifeService.ActivityInfo";
LifeService.ActivityInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
LifeService.ActivityInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
LifeService.ActivityInfo._readFrom = function (is) {
    var tmp = new LifeService.ActivityInfo;
    tmp.activityId = is.readString(0, true, "");
    tmp.sponsor = is.readString(1, true, "");
    tmp.clubId = is.readString(2, true, "");
    tmp.targetId = is.readString(3, true, "");
    tmp.createTime = is.readString(4, false, "");
    tmp.startTime = is.readString(5, false, "");
    tmp.stopTime = is.readString(6, false, "");
    tmp.registryStartTime = is.readString(7, false, "");
    tmp.registryStopTime = is.readString(8, false, "");
    tmp.content = is.readString(9, false, "");
    return tmp;
};
LifeService.ActivityInfo.prototype._writeTo = function (os) {
    os.writeString(0, this.activityId);
    os.writeString(1, this.sponsor);
    os.writeString(2, this.clubId);
    os.writeString(3, this.targetId);
    os.writeString(4, this.createTime);
    os.writeString(5, this.startTime);
    os.writeString(6, this.stopTime);
    os.writeString(7, this.registryStartTime);
    os.writeString(8, this.registryStopTime);
    os.writeString(9, this.content);
};
LifeService.ActivityInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
LifeService.ActivityInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
LifeService.ActivityInfo.prototype.toObject = function() { 
    return {
        "activityId" : this.activityId,
        "sponsor" : this.sponsor,
        "clubId" : this.clubId,
        "targetId" : this.targetId,
        "createTime" : this.createTime,
        "startTime" : this.startTime,
        "stopTime" : this.stopTime,
        "registryStartTime" : this.registryStartTime,
        "registryStopTime" : this.registryStopTime,
        "content" : this.content
    };
};
LifeService.ActivityInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "activityId") && (this.activityId = json.activityId);
    _hasOwnProperty.call(json, "sponsor") && (this.sponsor = json.sponsor);
    _hasOwnProperty.call(json, "clubId") && (this.clubId = json.clubId);
    _hasOwnProperty.call(json, "targetId") && (this.targetId = json.targetId);
    _hasOwnProperty.call(json, "createTime") && (this.createTime = json.createTime);
    _hasOwnProperty.call(json, "startTime") && (this.startTime = json.startTime);
    _hasOwnProperty.call(json, "stopTime") && (this.stopTime = json.stopTime);
    _hasOwnProperty.call(json, "registryStartTime") && (this.registryStartTime = json.registryStartTime);
    _hasOwnProperty.call(json, "registryStopTime") && (this.registryStopTime = json.registryStopTime);
    _hasOwnProperty.call(json, "content") && (this.content = json.content);
    return this;
};
LifeService.ActivityInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
LifeService.ActivityInfo.new = function () {
    return new LifeService.ActivityInfo();
};
LifeService.ActivityInfo.create = function (is) {
    return LifeService.ActivityInfo._readFrom(is);
};


