// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tars2node(20190529)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "ServerStatus.tars" by Structure Mode
// **********************************************************************

/* eslint-disable */

"use strict";


var LifeService = LifeService || {};
module.exports.LifeService = LifeService;

LifeService.ErrorCode = {
    "SUCCESS" : 200,
    "USEREXIST" : 301001,
    "PHONEEXIST" : 301002,
    "CLUBEXIST" : 301003,
    "MANAGEREXIST" : 301004,
    "USERAPPLIED" : 301005,
    "ACTIVITYEXIST" : 301006,
    "RECORDEXIST" : 301007,
    "USERNOTEXIST" : 404001,
    "CLUBNOTEXIST" : 404002,
    "MANAGERNOTEXIST" : 404003,
    "ACTIVITYNOTEXIST" : 404004,
    "APPLYNOTEXIST" : 404005,
    "RECORDNOTEXIST" : 404006,
    "SERVERERROR" : 500
};
LifeService.ErrorCode._classname = "LifeService.ErrorCode";
LifeService.ErrorCode._write = function(os, tag, val) { return os.writeInt32(tag, val); };
LifeService.ErrorCode._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };


