// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tars2node(20190529)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "UserInfoService.tars" by Client Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;
var _TARS_MODULE_A_ = require("./DataServiceTars.js");

var _makeError = function (data, message, type) {
    var error = new Error(message || "");
    error.request = data.request;
    error.response = {
        "costtime" : data.request.costtime
    };
    if (type === TarsError.CLIENT.DECODE_ERROR) {
        error.name = "DECODE_ERROR";
        error.response.error = {
            "code" : type,
            "message" : message
        };
    } else {
        error.name = "RPC_ERROR";
        error.response.error = data.error;
    }
    return error;
};

var LifeService = LifeService || {};
module.exports.LifeService = LifeService;

LifeService.UserInfoServiceProxy = function () {
    this._name    = undefined;
    this._worker  = undefined;
};

LifeService.UserInfoServiceProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
};

LifeService.UserInfoServiceProxy.prototype.getTimeout = function () {
    return this._worker.timeout;
};

LifeService.UserInfoServiceProxy.prototype.setVersion = function (iVersion) {
    this._worker.version = iVersion;
};

LifeService.UserInfoServiceProxy.prototype.getVersion = function () {
    return this._worker.version;
};

var __LifeService_UserInfoService$GetGroupList$IF = {
    "name" : "GetGroupList",
    "return" : "int32",
    "arguments" : [{
        "name" : "groupInfo",
        "class" : "map(int32, string)",
        "direction" : "out"
    }]
};

var __LifeService_UserInfoService$GetGroupList$IE = function () {
    var os = new TarsStream.TarsOutputStream();
    return os.getBinBuffer();
};

var __LifeService_UserInfoService$GetGroupList$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "groupInfo" : is.readMap(1, true, TarsStream.Map(TarsStream.Int32, TarsStream.String))
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$GetGroupList$PE = function (__$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    return tup;
};

var __LifeService_UserInfoService$GetGroupList$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "groupInfo" : tup.readMap("groupInfo", TarsStream.Map(TarsStream.Int32, TarsStream.String))
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$GetGroupList$ER = function (data) {
    throw _makeError(data, "Call UserInfoService::GetGroupList failed");
};

LifeService.UserInfoServiceProxy.prototype.GetGroupList = function () {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("GetGroupList", __LifeService_UserInfoService$GetGroupList$PE(version), arguments[arguments.length - 1], __LifeService_UserInfoService$GetGroupList$IF).then(__LifeService_UserInfoService$GetGroupList$PD, __LifeService_UserInfoService$GetGroupList$ER);
    } else {
        return this._worker.tars_invoke("GetGroupList", __LifeService_UserInfoService$GetGroupList$IE(), arguments[arguments.length - 1], __LifeService_UserInfoService$GetGroupList$IF).then(__LifeService_UserInfoService$GetGroupList$ID, __LifeService_UserInfoService$GetGroupList$ER);
    }
};
LifeService.UserInfoServiceProxy.GetGroupList = __LifeService_UserInfoService$GetGroupList$IF;

var __LifeService_UserInfoService$GetUserPermissionInfo$IF = {
    "name" : "GetUserPermissionInfo",
    "return" : "int32",
    "arguments" : [{
        "name" : "wx_id",
        "class" : "string",
        "direction" : "in"
    }]
};

var __LifeService_UserInfoService$GetUserPermissionInfo$IE = function (wx_id) {
    var os = new TarsStream.TarsOutputStream();
    os.writeString(1, wx_id);
    return os.getBinBuffer();
};

var __LifeService_UserInfoService$GetUserPermissionInfo$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0)
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$GetUserPermissionInfo$PE = function (wx_id, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeString("wx_id", wx_id);
    return tup;
};

var __LifeService_UserInfoService$GetUserPermissionInfo$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0)
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$GetUserPermissionInfo$ER = function (data) {
    throw _makeError(data, "Call UserInfoService::GetUserPermissionInfo failed");
};

LifeService.UserInfoServiceProxy.prototype.GetUserPermissionInfo = function (wx_id) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("GetUserPermissionInfo", __LifeService_UserInfoService$GetUserPermissionInfo$PE(wx_id, version), arguments[arguments.length - 1], __LifeService_UserInfoService$GetUserPermissionInfo$IF).then(__LifeService_UserInfoService$GetUserPermissionInfo$PD, __LifeService_UserInfoService$GetUserPermissionInfo$ER);
    } else {
        return this._worker.tars_invoke("GetUserPermissionInfo", __LifeService_UserInfoService$GetUserPermissionInfo$IE(wx_id), arguments[arguments.length - 1], __LifeService_UserInfoService$GetUserPermissionInfo$IF).then(__LifeService_UserInfoService$GetUserPermissionInfo$ID, __LifeService_UserInfoService$GetUserPermissionInfo$ER);
    }
};
LifeService.UserInfoServiceProxy.GetUserPermissionInfo = __LifeService_UserInfoService$GetUserPermissionInfo$IF;

var __LifeService_UserInfoService$SignIn$IF = {
    "name" : "SignIn",
    "return" : "int32",
    "arguments" : [{
        "name" : "wx_id",
        "class" : "string",
        "direction" : "in"
    }, {
        "name" : "sRsp",
        "class" : "LifeService.UserInfo",
        "direction" : "out"
    }]
};

var __LifeService_UserInfoService$SignIn$IE = function (wx_id) {
    var os = new TarsStream.TarsOutputStream();
    os.writeString(1, wx_id);
    return os.getBinBuffer();
};

var __LifeService_UserInfoService$SignIn$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "sRsp" : is.readStruct(2, true, _TARS_MODULE_A_.LifeService.UserInfo)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$SignIn$PE = function (wx_id, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeString("wx_id", wx_id);
    return tup;
};

var __LifeService_UserInfoService$SignIn$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "sRsp" : tup.readStruct("sRsp", _TARS_MODULE_A_.LifeService.UserInfo)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$SignIn$ER = function (data) {
    throw _makeError(data, "Call UserInfoService::SignIn failed");
};

LifeService.UserInfoServiceProxy.prototype.SignIn = function (wx_id) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("SignIn", __LifeService_UserInfoService$SignIn$PE(wx_id, version), arguments[arguments.length - 1], __LifeService_UserInfoService$SignIn$IF).then(__LifeService_UserInfoService$SignIn$PD, __LifeService_UserInfoService$SignIn$ER);
    } else {
        return this._worker.tars_invoke("SignIn", __LifeService_UserInfoService$SignIn$IE(wx_id), arguments[arguments.length - 1], __LifeService_UserInfoService$SignIn$IF).then(__LifeService_UserInfoService$SignIn$ID, __LifeService_UserInfoService$SignIn$ER);
    }
};
LifeService.UserInfoServiceProxy.SignIn = __LifeService_UserInfoService$SignIn$IF;

var __LifeService_UserInfoService$SignUp$IF = {
    "name" : "SignUp",
    "return" : "int32",
    "arguments" : [{
        "name" : "wx_id",
        "class" : "string",
        "direction" : "in"
    }, {
        "name" : "userInfo",
        "class" : "LifeService.UserInfo",
        "direction" : "in"
    }, {
        "name" : "retCode",
        "class" : "int32",
        "direction" : "out"
    }]
};

var __LifeService_UserInfoService$SignUp$IE = function (wx_id, userInfo) {
    var os = new TarsStream.TarsOutputStream();
    os.writeString(1, wx_id);
    os.writeStruct(2, userInfo);
    return os.getBinBuffer();
};

var __LifeService_UserInfoService$SignUp$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "retCode" : is.readInt32(3, true, 0)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$SignUp$PE = function (wx_id, userInfo, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeString("wx_id", wx_id);
    tup.writeStruct("userInfo", userInfo);
    return tup;
};

var __LifeService_UserInfoService$SignUp$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "retCode" : tup.readInt32("retCode")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$SignUp$ER = function (data) {
    throw _makeError(data, "Call UserInfoService::SignUp failed");
};

LifeService.UserInfoServiceProxy.prototype.SignUp = function (wx_id, userInfo) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("SignUp", __LifeService_UserInfoService$SignUp$PE(wx_id, userInfo, version), arguments[arguments.length - 1], __LifeService_UserInfoService$SignUp$IF).then(__LifeService_UserInfoService$SignUp$PD, __LifeService_UserInfoService$SignUp$ER);
    } else {
        return this._worker.tars_invoke("SignUp", __LifeService_UserInfoService$SignUp$IE(wx_id, userInfo), arguments[arguments.length - 1], __LifeService_UserInfoService$SignUp$IF).then(__LifeService_UserInfoService$SignUp$ID, __LifeService_UserInfoService$SignUp$ER);
    }
};
LifeService.UserInfoServiceProxy.SignUp = __LifeService_UserInfoService$SignUp$IF;

var __LifeService_UserInfoService$Test$IF = {
    "name" : "Test",
    "return" : "int32",
    "arguments" : [{
        "name" : "TestStr",
        "class" : "string",
        "direction" : "out"
    }]
};

var __LifeService_UserInfoService$Test$IE = function () {
    var os = new TarsStream.TarsOutputStream();
    return os.getBinBuffer();
};

var __LifeService_UserInfoService$Test$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "TestStr" : is.readString(1, true, "")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$Test$PE = function (__$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    return tup;
};

var __LifeService_UserInfoService$Test$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "TestStr" : tup.readString("TestStr")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __LifeService_UserInfoService$Test$ER = function (data) {
    throw _makeError(data, "Call UserInfoService::Test failed");
};

LifeService.UserInfoServiceProxy.prototype.Test = function () {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("Test", __LifeService_UserInfoService$Test$PE(version), arguments[arguments.length - 1], __LifeService_UserInfoService$Test$IF).then(__LifeService_UserInfoService$Test$PD, __LifeService_UserInfoService$Test$ER);
    } else {
        return this._worker.tars_invoke("Test", __LifeService_UserInfoService$Test$IE(), arguments[arguments.length - 1], __LifeService_UserInfoService$Test$IF).then(__LifeService_UserInfoService$Test$ID, __LifeService_UserInfoService$Test$ER);
    }
};
LifeService.UserInfoServiceProxy.Test = __LifeService_UserInfoService$Test$IF;



